apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "formbuilder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "formbuilder.name" . }}
    helm.sh/chart: {{ include "formbuilder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.formbuilder.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "formbuilder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "formbuilder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: builder
        image: "{{ .Values.formbuilder.image.repository }}:{{ .Values.formbuilder.image.tag }}"
        imagePullPolicy: {{ .Values.formbuilder.image.pullPolicy }}
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        volumeMounts:
        - name: config-volume
          mountPath: /config
        ports:
          - name: http
            containerPort: {{ .Values.formbuilder.service.targetPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.formbuilder.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.formbuilder.service.targetPort }}
        env:
          - name: PORT
            value: {{ .Values.formbuilder.service.targetPort }}
        resources:
          {{- toYaml .Values.formbuilder.resources | nindent 10 }}
      {{- with .Values.formbuilder.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.formbuilder.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.formbuilder.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      imagePullSecrets:
      - name: {{ .Values.formbuilder.imageCredentials.name }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "formbuilder.fullname" . }}
