{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.formbuilder.imageCredentials.registry .Values.formbuilder.imageCredentials.username .Values.formbuilder.imageCredentials.password .Values.formbuilder.imageCredentials.email (printf "%s:%s" .Values.formbuilder.imageCredentials.username .Values.formbuilder.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
