{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.formbuilder.imageCredentials.registry (printf "%s:%s" .Values.formbuilder.imageCredentials.username .Values.formbuilder.imageCredentials.password | b64enc) | b64enc }}
{{- end }}
