---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{ include "formbuilder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "formbuilder.name" . }}
    helm.sh/chart: {{ include "formbuilder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  egress:
    - {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-external
      ports:
        - port: {{ .Values.formbuilder.service.targetPort }}
          protocol: TCP
  podSelector:
    matchLabels:
      name: {{ include "formbuilder.fullname" . }}
  policyTypes:
    - Ingress
    - Egress
