{{- $service := .Values.formbuilder.service -}}
apiVersion: v1
kind: Service
metadata:
  app.kubernetes.io/name: {{ include "formbuilder.name" . }}
  helm.sh/chart: {{ include "formbuilder.chart" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with $service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "formbuilder.name" . }}
    chart: {{ template "formbuilder.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with $service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ $service.type }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
    {{- if and (eq "NodePort" $service.type) $service.nodePort }}
      nodePort: {{ $service.nodePort }}
    {{- end }}
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ template "formbuilder.name" . }}
    app.kubernetes.io/name: {{ template "formbuilder.name" . }}
