---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{ include "docs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "docs.name" . }}
    helm.sh/chart: {{ include "docs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  egress:
    - {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Values.docs.ingress.namespace }}
      ports:
        - port: {{ .Values.docs.service.targetPort }}
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "docs.name" . }}
  policyTypes:
    - Ingress
    - Egress
