# Default values for docs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
docs:
  replicaCount: 1

  image:
    repository: digitalpatterns/docs
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: false
    secure: false
    namespace: nginx-external
    annotations: {}
    labels: {}
    hosts:
      - docs.example.com
    tls: []
