apiVersion: v1
kind: ConfigMap
metadata:
  name: formbuilder
  labels:
    app: formbuilder
data:
  appConfig.json: |
    {
      "environments": [{
        "id": "local",
        "label": "Local",
        "url": "http://formio.lodev.xyz",
        "description": "local development environment",
        "service": {
          "formio": {
            "username": "me@lodev.xyz",
            "password": "secret"
          },
          "keycloak": {
            "tokenUrl": "http://keycloak.lodev.xyz/auth/realms/dev/protocol/openid-connect/token",
            "clientId": "service-account",
            "secret": "ed041195-fdf8-424b-a061-2081ea5067f1"
          }
        },
        "editable": true,
        "variable-replacements": [
          {
            "{$.environmentContext.platformDataUrl}": "http://www.google.co.uk"
          },
          {
            "{$.staffDetailsContext.staffId}": "{{guid}}"
          },
          {
            "{$.keycloakContext.givenName}": "{{firstName}}"
          },
          {
            "{$.keycloakContext.familyName}": "{{lastName}}"
          }
        ]
      },
        {
          "id": "dev",
          "label": "Development",
          "url": "https://formio.elf79.dev",
          "description": "Elf Dev environment",
          "service": {
            "formio": {
              "username": "me@lodev.xyz",
              "password": "secret"
            },
            "keycloak": {
              "tokenUrl": "https://keycloak.elf79.dev/auth/realms/elf/protocol/openid-connect/token",
              "clientId": "form-builder",
              "secret": "d78fcb80-ff1b-45af-be99-674f4f067950"
            }
          },
          "editable": true,
        "variable-replacements": [
          {
            "{$.environmentContext.platformDataUrl}": "http://www.google.co.uk"
          },
          {
            "{$.staffDetailsContext.staffId}": "{{guid}}"
          },
          {
            "{$.keycloakContext.givenName}": "{{firstName}}"
          },
          {
            "{$.keycloakContext.familyName}": "{{lastName}}"
          }
        ]
        },
        {
          "id": "staging",
          "label": "Staging",
          "url": "http://formio.lodev.xyz",
          "description": "Staging environment",
          "service": {
            "formio": {
              "username": "me@lodev.xyz",
              "password": "secret"
            },
            "keycloak": {
              "tokenUrl": "http://keycloak.lodev.xyz/auth/realms/dev/protocol/openid-connect/token",
              "clientId": "service-account",
              "secret": "ed041195-fdf8-424b-a061-2081ea5067f1"
            }
          },
          "editable": false
        },
        {
          "id": "prod",
          "label": "Production",
          "url": "http://formio.lodev.xyz",
          "approvalUrl" : "http://localhost:8001/form",
          "description": "Prod environment",
          "service": {
            "keycloak": {
              "tokenUrl": "http://keycloak.lodev.xyz/auth/realms/dev/protocol/openid-connect/token",
              "clientId": "service-account",
              "secret": "ed041195-fdf8-424b-a061-2081ea5067f1"
            },
            "formio": {
              "username": "me@lodev.xyz",
              "password": "secret"
            }
          },
          "editable": false
        }
      ],
      "gov-uk-enabled" : true,
      "keycloak": {
        "authUrl": "http://keycloak.lodev.xyz/auth",
        "clientId": "platform-ui",
        "realm": "dev"
      }
    }
