certs:
  image:
    repository: quay.io/ukhomeofficedigital/borders-cfssl-sidekick
    tag: bd4901b5a28c
    pullPolicy: Always
  internalCaUrl: https://ca.kube-tls.svc.cluster.local

proxy:
  image:
    repository: quay.io/ukhomeofficedigital/nginx-proxy
    tag: latest
    pullPolicy: Always
  env:
    port: 8080
    noLoggingUrlParams: "FALSE"
    noLoggingBody: "FALSE"
    noLoggingResponse: "FALSE"
    statsdMetrics: "TRUE"

formbuilder:
  replicaCount: 1
  imageCredentials:
    name: formbuilder-credentials
    registry: https://index.docker.io/v1/
    username: username
    password: password
    email: a@b.com
  image:
    repository: digitalpatterns/form-builder
    tag: latest
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  securityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 1
  resources: {}
  service:
    type: ClusterIP
    port: 443
    targetPort: 10443
  ingress:
    enabled: false
    namespace: nginx-external
    annotations: {}
    labels: {}
    hosts:
      - formbuilder.example.com
    tls: []
