formbuilder:
  replicaCount: 1
  image:
    repository: docker/
    tag: stable
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  securityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 1
  resources: {}
  service:
    type: ClusterIP
    port: http
    targetPort: 8101
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    hosts:
      - formbuilder.example.com
    tls: []
